export const AUTH_ADDRESS = process.env.VUE_APP_AUTH_URL;
export const SPECIALIZATIONS_ADDRESS = process.env.VUE_APP_SPECIALIZATIONS_URL;
export const DOCTORS_ADDRESS = process.env.VUE_APP_DOCTORS_URL;
export const PATIENTS_ADDRESS = process.env.VUE_APP_PATIENTS_URL;
export const APPOINTMENTS_ADDRESS = process.env.VUE_APP_APPOINTMENTS_URL;