apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: patients
  template:
    metadata:
      labels:
        app: patients
    spec:
      containers:
        - name: patients
          image: zickooo/hospital-manager-patients:latest
          imagePullPolicy: Always
          env:
            - name: APPOINTMENT_ADDRESS
              value: "appointments-service.default:5005"

---

apiVersion: v1
kind: Service
metadata:
  name: patients-service
spec:
  selector:
    app: patients
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004